INSERT INTO DEPT VALUES (50, 'IT', 'SEOUL');
INSERT INTO EMP (EMPNO, ENAME, JOB, HIREDATE, SAL, DEPTNO)
  VALUES (8000, 'LEE', 'MANAGER', SYSDATE, 9000, 50);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
  VALUES (9000, 'HONG', 'MANAGER', 8000, SYSDATE, 9000, 50);
SELECT * FROM EMP WHERE DEPTNO IN (10,20);
SELECT * FROM DEPT;
COMMIT;