DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    ID VARCHAR2(100) PRIMARY KEY,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    POSTCODE VARCHAR2(10),
    ADDRESS VARCHAR2(300),
    DETAILADDRESS VARCHAR2(300)
);
-- join
INSERT INTO MEMBER 
    VALUES ('aaa','1','홍길동','03780',
    '서울 서대문구 신촌로 141','좋은 빌딩 202호');
-- list
SELECT * FROM MEMBER;
commit;