-- 좌석 예약
DROP TABLE SEAT;
CREATE TABLE SEAT (
    SEATID VARCHAR2(10),
    MID VARCHAR2(100)
);
INSERT INTO SEAT VALUES ('a1', 'aaa');
INSERT INTO SEAT VALUES ('a2', 'aaa');
INSERT INTO SEAT VALUES ('a6', 'aaa');
INSERT INTO SEAT VALUES ('a5', 'bbb');
INSERT INTO SEAT VALUES ('a3', 'aaa');
INSERT INTO SEAT VALUES ('a4', 'aaa');
SELECT SEATID FROM SEAT where mid='aaa';
COMMIT;