-- TABLE & SEQUENCE DROP
DROP TABLE MVC_BOARD;
DROP SEQUENCE MVC_BOARD_SEQ;
-- TABLE & SEQUENCE CREATE
CREATE TABLE MVC_BOARD(
  bID   NUMBER(6),
  bNAME VARCHAR2(50) NOT NULL,
  bTITLE VARCHAR2(100) NOT NULL,
  bCONTENT VARCHAR2(1000),
  bDATE    DATE DEFAULT SYSDATE NOT NULL, -- 작성일
  bHIT     NUMBER(6) DEFAULT 0 NOT NULL,  -- 조회수
  bGROUP   NUMBER(6) NOT NULL, -- 원글이면 BID와 같고, 답변글의 경우 원글의 BGROUP과 같다
  bSTEP    NUMBER(3) NOT NULL, -- 같은 그룹내 출력 순서
  bINDENT  NUMBER(3) NOT NULL, -- 들여쓰기 정도
  bIP      VARCHAR2(20),
  PRIMARY KEY(BID)
);
CREATE SEQUENCE MVC_BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
-- DUMMY DATA
SELECT * FROM MVC_BOARD;
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
 VALUES (MVC_BOARD_SEQ.NEXTVAL, '홍','제목', NULL, MVC_BOARD_SEQ.CURRVAL, 0,0,'192.1.1.1');
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
 VALUES (MVC_BOARD_SEQ.NEXTVAL, '김','비와', NULL, MVC_BOARD_SEQ.CURRVAL, 0,0,'192.1.1.2');
SELECT * FROM MVC_BOARD;
  -- 2번글의 답글
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
 VALUES (MVC_BOARD_SEQ.NEXTVAL, '이','답','답', 2, 1, 1, '127.0.0.1');

-- DAO에 들어갈 QUERY
-- 1. 글목록(startRow ~ endRow까지)
SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP;
SELECT * 
  FROM (SELECT ROWNUM RN, A.* 
        FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP) A)
  WHERE RN BETWEEN 2 AND 3;

-- 2. 전체 글 갯수
SELECT COUNT(*) FROM MVC_BOARD;

-- 3. 원글 쓰기
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
 VALUES (MVC_BOARD_SEQ.NEXTVAL, '홍','TITLE', NULL, MVC_BOARD_SEQ.CURRVAL, 0,0,'192.1.1.1');

-- 4. 






