-- NULL
SELECT * FROM (SELECT ROWNUM RN, A.*, (SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = A.GROUP_BID) REP_CNT
    FROM (SELECT * FROM GROUP_BOARD WHERE GROUP_BID = '11113' ORDER BY GROUP_BOARD_RDATE DESC) A) WHERE RN BETWEEN 1 AND 10;

-- ALL
SELECT * FROM (SELECT ROWNUM RN, A.*, (SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = A.GROUP_BID) REP_CNT
    FROM (SELECT * FROM GROUP_BOARD WHERE GROUP_BID = '11113' 
                                    OR MID LIKE '%'||'t'||'%' 
                                    OR GROUP_BOARD_TITLE LIKE '%'||'코'||'%' 
                                    OR GROUP_BOARD_CONTENT LIKE '%'||'이'||'%' 
                            ORDER BY GROUP_BOARD_RDATE DESC) A) WHERE RN BETWEEN 1 AND 10;

-- MID
SELECT * FROM (SELECT ROWNUM RN, A.*, (SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = A.GROUP_BID) REP_CNT
    FROM (SELECT * FROM GROUP_BOARD WHERE GID = '1' 
                                    AND MID LIKE '%'||'t'||'%' 
                            ORDER BY GROUP_BOARD_RDATE DESC) A) WHERE RN BETWEEN 1 AND 10;
                            
-- TITLE
SELECT * FROM (SELECT ROWNUM RN, A.*, (SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = A.GROUP_BID) REP_CNT
    FROM (SELECT * FROM GROUP_BOARD WHERE GID = '1' 
                                    AND GROUP_BOARD_TITLE LIKE '%'||'코'||'%' 
                            ORDER BY GROUP_BOARD_RDATE DESC) A) WHERE RN BETWEEN 1 AND 10;
-- CONTENT
SELECT * FROM (SELECT ROWNUM RN, A.*, (SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = A.GROUP_BID) REP_CNT
    FROM (SELECT * FROM GROUP_BOARD WHERE GID = '1' 
                                    AND GROUP_BOARD_CONTENT LIKE '%'||'이'||'%' 
                            ORDER BY GROUP_BOARD_RDATE DESC) A) WHERE RN BETWEEN 1 AND 10;
-- HIT
SELECT * FROM (SELECT ROWNUM RN, A.*, (SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = A.GROUP_BID) REP_CNT
    FROM (SELECT * FROM GROUP_BOARD WHERE GID = '1' 
                            ORDER BY GROUP_BOARD_HIT DESC) A) WHERE RN BETWEEN 1 AND 10;
                            
-- LIKE
SELECT * FROM (SELECT ROWNUM RN, A.*, (SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = A.GROUP_BID) REP_CNT
    FROM (SELECT * FROM GROUP_BOARD WHERE GID = '1' 
                            ORDER BY GROUP_BOARD_LIKE DESC) A) WHERE RN BETWEEN 1 AND 10;
                            
-- count (all)
SELECT COUNT(*) FROM GROUP_BOARD WHERE GID = '1';

-- count (mid)
SELECT COUNT(*) FROM GROUP_BOARD WHERE GID = '1' AND MID LIKE '%'||'test1-1'||'%';

-- count (title)
SELECT COUNT(*) FROM GROUP_BOARD WHERE GID = '1' AND GROUP_BOARD_TITLE LIKE '%'||' '||'%';

-- count (content)
SELECT COUNT(*) FROM GROUP_BOARD WHERE GID = '1' AND GROUP_BOARD_CONTENT LIKE '%'||' '||'%';

-- insert
INSERT INTO GROUP_BOARD VALUES (GROUP_BOARD_SEQ.NEXTVAL, '1', 'test1-1', '스터디 시작!', '열심히 합시당', NULL, 2, '182.11.2', 0, SYSDATE);

-- hitUp
UPDATE GROUP_BOARD SET GROUP_BOARD_HIT = GROUP_BOARD_HIT + 1 WHERE GROUP_BID = '11111';

-- detail
SELECT * FROM GROUP_BOARD WHERE GROUP_BID = '11111';

-- modify
UPDATE GROUP_BOARD SET GROUP_BOARD_TITLE = '스터디 시작',
                        GROUP_BOARD_CONTENT = '열심히 해요',
                        GROUP_BOARD_FILE = '11111.JPG',
                        GROUP_BOARD_IP = '192.0.0.1',
                        GROUP_BOARD_RDATE = SYSDATE
                    WHERE GROUP_BID = '11111';
                    
-- delete
DELETE FROM GROUP_BOARD WHERE GROUP_BID = '11110';