-- NULL
SELECT * FROM (SELECT ROWNUM RN, A.*
    FROM (SELECT * FROM GROUP_BOARD_REPLY WHERE GROUP_BID = '11114' ORDER BY GROUP_BOARD_REP_RDATE) A) WHERE RN BETWEEN 1 AND 10;
                            
-- count (all)
SELECT COUNT(*) FROM GROUP_BOARD_REPLY WHERE GROUP_BID = '11114';

-- insert
INSERT INTO GROUP_BOARD_REPLY VALUES (GROUP_BOARD_REP_SEQ.NEXTVAL, '11114', 'test1-1', '저는 진짜 열심히 할거예요', 0, SYSDATE);

-- modify
UPDATE GROUP_BOARD_REPLY SET GROUP_BOARD_REP_CONTENT = '제가 더 열심히 할거거든여?',
                            GROUP_BOARD_REP_RDATE = SYSDATE 
                        WHERE GROUP_REPID = '11112';
                    
-- delete
DELETE FROM GROUP_BOARD_REPLY WHERE GROUP_REPID = '11110';