SELECT SCHEDULE_SEQ.CURRVAL FROM DUAL;

-- totalSchedule
SELECT * FROM SCHEDULE WHERE GID = 1;

-- detailSchedule
SELECT * FROM SCHEDULE WHERE SCD_ID = 11111;

-- 스터디 가입 후 (지나지 않은) 전체 일정 갯수 파악 *달성도 체크용*
SELECT SCD_ID FROM SCHEDULE WHERE GID = 1 AND SCD_END > SYSDATE;

-- 달성여부 insert
INSERT INTO SCD_ACHIVE VALUES ('11111', 'test1-1', 'N');

-- updateAchive
UPDATE SCD_ACHIVE SET SCD_ACHIVE = 'Y' WHERE SCD_ID = 11115;

-- 달성율 확인
SELECT CASE WHEN NVL((SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1), 0) > 0 THEN ROUND((SELECT COUNT(*) FROM SCD_ACHIVE WHERE SCD_ACHIVE = 'Y' AND MID = 'test1-1') / (SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1) * 100) ELSE 0 END||'%' "참여율" FROM DUAL;

SELECT ROUND((CASE WHEN NVL((SELECT COUNT(*) FROM SCD_ACHIVE WHERE SCD_ACHIVE = 'Y' AND MID = 'test1-1'),0) > 0 THEN (SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1) / (SELECT COUNT(*) FROM SCD_ACHIVE WHERE SCD_ACHIVE = 'Y' AND MID = 'test1-1'))*100 ELSE 0 END AS)||'%' "참여율" FROM DUAL;