-- 
DROP TABLE BOOK;
DROP TABLE BOOKCATEGORY;
CREATE TABLE BOOKCATEGORY(
  CATEGORY_CODE NUMBER(3) PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(50) UNIQUE NOT NULL,
  OFFICE_LOC    VARCHAR2(50) NOT NULL
);
CREATE TABLE BOOK(
  BOOK_ID VARCHAR2(30) PRIMARY KEY,
  CATEGORY_CODE NUMBER(3) REFERENCES BOOKCATEGORY(CATEGORY_CODE),
  BOOK_TITLE VARCHAR2(100) NOT NULL,
  BOOK_PRICE NUMBER(6) NOT NULL,
  BOOK_COUNT NUMBER(4) NOT NULL,
  AUTHOR     VARCHAR2(30) NOT NULL,
  PUBLISHING VARCHAR2(30) NOT NULL,
  BOOK_IMAGE1 VARCHAR2(100) DEFAULT 'onImg.png' NOT NULL,
  BOOK_IMAGE2 VARCHAR2(100) DEFAULT 'NOTHING.JPG' NOT NULL,
  BOOK_DISCOUNT NUMBER(3) DEFAULT 0,
  BOOK_RDATE DATE DEFAULT SYSDATE NOT NULL
);









