DROP TABLE FRIEND;
CREATE TABLE FRIEND(
  NO NUMBER(3) PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  TEL VARCHAR2(30) NOT NULL,
  ADDR VARCHAR2(300)
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 999 NOCACHE NOCYCLE;
INSERT INTO FRIEND 
  VALUES (FRIEND_SQ.NEXTVAL, '홍길동', '010-9999-9999', '서울');
  