-- ex1
INSERT INTO DEPT VALUES (60, 'IT', 'SEOUL');
SELECT * FROM DEPT WHERE DEPTNO>40;
COMMIT;
-- ex2.
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=99;
INSERT INTO DEPT VALUES (60, 'IT', 'SEOUL');
SELECT * FROM DEPT WHERE DEPTNO>40;

-- update
UPDATE DEPT SET DNAME='MARKETING', LOC='INCHON'
  WHERE DEPTNO=52;
COMMIT;

-- UPDATE2
SELECT * FROM DEPT WHERE DEPTNO=52;
UPDATE DEPT SET DNAME='MARKETING', LOC='INCHON'
  WHERE DEPTNO=52;
COMMIT;

-- DELETE
DELETE FROM DEPT WHERE DEPTNO=99;









