DROP TABLE FRIEND;
CREATE TABLE FRIEND(
  NO NUMBER(3) PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  TEL VARCHAR2(30) NOT NULL,
  ADDR VARCHAR2(300)
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 999 NOCACHE NOCYCLE;
INSERT INTO FRIEND 
  VALUES (FRIEND_SQ.NEXTVAL, '홍길동', '010-9999-9999', '서울');
INSERT INTO FRIEND 
  VALUES (FRIEND_SQ.NEXTVAL, '신안동', '010-8888-8888', '안양');
SELECT * FROM FRIEND ORDER BY NO DESC; -- 출력 기준
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM FRIEND ORDER BY NO DESC) A)
  WHERE RN BETWEEN 2 AND 8; -- DAO에 들어갈 SQL
SELECT COUNT(*) FROM FRIEND;
COMMIT;