DROP TABLE SALES;
DROP SEQUENCE SALES_NO_SQ;
CREATE TABLE SALES(
  NO NUMBER(4) PRIMARY KEY,
  SDATE DATE NOT NULL, -- 매출 날
  AMOUNT NUMBER(9) DEFAULT 0 NOT NULL -- 매출액
);
CREATE SEQUENCE SALES_NO_SQ MAXVALUE 9999 NOCACHE NOCYCLE;
INSERT INTO SALES VALUES (SALES_NO_SQ.NEXTVAL, TO_DATE('23/04/04 09:30', 'RR/MM/DD HH24:MI'), 10000);
INSERT INTO SALES VALUES (SALES_NO_SQ.NEXTVAL, TO_DATE('23/04/29 09:30', 'RR/MM/DD HH24:MI'), 10000);
INSERT INTO SALES VALUES (SALES_NO_SQ.NEXTVAL, TO_DATE('23/04/29 12:30', 'RR/MM/DD HH24:MI'), 10000);
INSERT INTO SALES VALUES (SALES_NO_SQ.NEXTVAL, TO_DATE('23/04/30 12:30', 'RR/MM/DD HH24:MI'), 10000);
INSERT INTO SALES VALUES (SALES_NO_SQ.NEXTVAL, TO_DATE('23/04/30 16:30', 'RR/MM/DD HH24:MI'), 10000);
INSERT INTO SALES VALUES (SALES_NO_SQ.NEXTVAL, TO_DATE('23/04/30 17:30', 'RR/MM/DD HH24:MI'), 55000);
INSERT INTO SALES VALUES (SALES_NO_SQ.NEXTVAL, '23/05/03', 20000);
SELECT * FROM SALES;
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';

SELECT LEVEL, ENAME FROM EMP START WITH MGR IS NULL CONNECT BY PRIOR EMPNO=MGR;

SELECT TO_DATE(SDATE) SDATE, SUM(AMOUNT) AMOUNT FROM SALES 
  WHERE sDATE BETWEEN SYSDATE-15 AND SYSDATE
  GROUP BY TO_DATE(SDATE)
  ORDER BY SDATE;  -- A
  
SELECT TO_DATE(SYSDATE-15 + LEVEL - 1) AS dt
   FROM dual 
CONNECT BY LEVEL <= 14; -- B
-- A와 B를 OUTER JOIN
SELECT B.DT, AMOUNT FROM 
  (SELECT TO_DATE(SDATE) SDATE, SUM(AMOUNT) AMOUNT FROM SALES 
  WHERE sDATE BETWEEN SYSDATE-15 AND SYSDATE
  GROUP BY TO_DATE(SDATE)
  ORDER BY SDATE) A, 
  (SELECT TO_DATE(SYSDATE-15 + LEVEL - 1) AS dt
   FROM dual 
    CONNECT BY LEVEL <= 15) B
  WHERE A.SDATE(+)=B.DT
  ORDER BY DT;