DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE ROOM CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE HOTEL CASCADE CONSTRAINTS;
DROP SEQUENCE RS_SQ;
CREATE TABLE HOTEL(
  HOTELCODE VARCHAR2(10) PRIMARY KEY,
  HOTELNAME VARCHAR2(50)
);
CREATE TABLE ROOM(
  ROOMCODE NUMBER(5) PRIMARY KEY,
  HOTELCODE VARCHAR2(10) REFERENCES HOTEL(HOTELCODE),
  ROOMNAME VARCHAR2(50),
  ROOMGRADE VARCHAR2(50),
  ROOMCOST NUMBER(10),
  ROOMLIMIT NUMBER(2),
  ROOMimg1 VARCHAR2(100)
);
INSERT INTO HOTEL VALUES ('h01', '신라호텔');
INSERT INTO HOTEL VALUES ('l01', '라마다호텔');
SELECT * FROM HOTEL;
INSERT INTO ROOM VALUES (1,'h01', '스위트','A',2000000,8,NULL);
INSERT INTO ROOM VALUES (2,'h01', '뭐좋은거','B',500000,6,NULL);
INSERT INTO ROOM VALUES (3,'h01', '그냥','C',100000,2,NULL);
INSERT INTO ROOM VALUES (4,'l01', '짱','A',100000,4,NULL);
INSERT INTO ROOM VALUES (5,'l01', '뭐','B',50000,2,NULL);
SELECT * FROM ROOM;
CREATE TABLE MEMBER(
  MID VARCHAR2(30) PRIMARY KEY,
  MPW VARCHAR2(30),
  MNAME VARCHAR2(30)
);
INSERT INTO MEMBER VALUES ('aaa','1','홍길동');
SELECT * FROM MEMBER;
CREATE TABLE RESERVATION(
  RESERVECODE NUMBER(5) PRIMARY KEY,
  ROOMCODE NUMBER(5) REFERENCES ROOM(ROOMCODE),
  MID VARCHAR2(30) REFERENCES MEMBER(MID),
  CHECKIN DATE NOT NULL,
  CHECKOUT DATE NOT NULL
);
CREATE SEQUENCE RS_SQ MAXVALUE 9999 NOCACHE;

INSERT INTO RESERVATION VALUES 
  (RS_SQ.NEXTVAL, 1, 'aaa', '23/05/01', '23/05/10');
INSERT INTO RESERVATION VALUES 
  (RS_SQ.NEXTVAL, 2, 'aaa', '23/08/01', '23/08/10');
-- 호텔 예약 정보
SELECT RESERVECODE, 
  (SELECT H.HOTELNAME FROM HOTEL H, ROOM R
    WHERE H.HOTELCODE=R.HOTELCODE AND R.ROOMCODE=RESERVATION.ROOMCODE) HOTELNAME,
  (SELECT r.roomname FROM HOTEL H, ROOM R
    WHERE H.HOTELCODE=R.HOTELCODE AND R.ROOMCODE=RESERVATION.ROOMCODE) roomname,
  ROOMCODE, MID, CHECKIN, CHECKOUT
  FROM RESERVATION;
SELECT * FROM RESERVATION
  WHERE ROOMCODE=2 AND
    ( (CHECKIN <= '23/08/10' AND CHECKOUT >= '23/08/11') OR
     (CHECKIN < '23/08/10' AND CHECKOUT < '23/08/11') OR
     (CHECKIN > '23/08/10' AND CHECKOUT > '23/08/11') OR
     (CHECKIN > '23/08/10' AND CHECKOUT < '23/08/11'));