DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE ROOM CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE HOTEL CASCADE CONSTRAINTS;
DROP SEQUENCE RS_SQ;
CREATE TABLE HOTEL(
  hotelCode VARCHAR2(10) PRIMARY KEY,
  hotelName VARCHAR2(50),
  hotelAddress VARCHAR2(255),
  hotelTel VARCHAR2(30),
  hotelImg1 VARCHAR2(255),
  hotelImg2 VARCHAR2(255),
  hotelImg3 VARCHAR2(255),
  hotelNotice CLOB, -- 이용안내
  hotelDetail CLOB, -- 상세정보
  hotelScore number(2,1) -- 평점
);
INSERT INTO HOTEL VALUES ('y01', '노보텔엠버서드','용산',null, null, null, null, null, null, 4.8);
INSERT INTO HOTEL VALUES ('s01', '라마다호텔','속초',null, null, null, null, null, null, 4.6);
CREATE TABLE ROOM(
  roomCODE NUMBER(5) PRIMARY KEY,
  hotelCODE VARCHAR2(10) REFERENCES HOTEL(HOTELCODE),
  roomNAME VARCHAR2(50),
  hotelGRADE VARCHAR2(50),
  hotelCOST NUMBER(10),
  hotelLIMIT NUMBER(2),
  hotelImg1 VARCHAR2(255),
  hotelImg2 VARCHAR2(255),
  hotelImg3 VARCHAR2(255),
  hotelImg4 VARCHAR2(255),
  hotelImg5 VARCHAR2(255)
);
SELECT * FROM HOTEL;
INSERT INTO ROOM VALUES (1,'y01', '프리미엄','A',3000000,6,NULL, NULL, NULL, NULL, NULL);
INSERT INTO ROOM VALUES (2,'y01', '디럭스','B',250000,4,NULL, NULL, NULL, NULL, NULL);
INSERT INTO ROOM VALUES (3,'y01', '수페리어룸','C',200000,2,NULL, NULL, NULL, NULL, NULL);
INSERT INTO ROOM VALUES (4,'s01', '디럭스패밀리더블','A',300000,6,NULL, NULL, NULL, NULL, NULL);
INSERT INTO ROOM VALUES (5,'s01', '스텐다드더블','B',150000,4,NULL, NULL, NULL, NULL, NULL);
INSERT INTO ROOM VALUES (6,'s01', '스텐다드트윈','C',100000,2,NULL, NULL, NULL, NULL, NULL);
SELECT * FROM ROOM;
CREATE TABLE MEMBER(
  MID VARCHAR2(30) PRIMARY KEY,
  MPW VARCHAR2(30),
  MNAME VARCHAR2(30)
);
INSERT INTO MEMBER VALUES ('aaa','1','홍길동');
SELECT * FROM MEMBER;
CREATE TABLE RESERVATION(
  RESERVECODE NUMBER(5) PRIMARY KEY,
  roomCODE NUMBER(5) REFERENCES ROOM(roomCODE),
  MID VARCHAR2(30) REFERENCES MEMBER(MID),
  CHECKIN DATE NOT NULL,
  CHECKOUT DATE NOT NULL,
  REVIEWsTATUS NUMBER(1) DEFAULT 0 -- 리뷰작성여부
);
CREATE SEQUENCE RS_SQ MAXVALUE 9999 NOCACHE;

INSERT INTO RESERVATION (reserveCode, roomCode, mId, checkIn, checkOut) VALUES 
  (RS_SQ.NEXTVAL, 1, 'aaa', '23/05/01', '23/05/10');
INSERT INTO RESERVATION (reserveCode, roomCode, mId, checkIn, checkOut) VALUES 
  (RS_SQ.NEXTVAL, 2, 'aaa', '23/08/01', '23/08/10');
-- 오늘 이후 호텔 예약 정보
SELECT RESERVECODE, 
  (SELECT H.HOTELNAME FROM HOTEL H, ROOM R
    WHERE H.HOTELCODE=R.HOTELCODE AND R.ROOMCODE=RESERVATION.ROOMCODE) HOTELNAME,
  (SELECT r.roomname FROM HOTEL H, ROOM R
    WHERE H.HOTELCODE=R.HOTELCODE AND R.ROOMCODE=RESERVATION.ROOMCODE) roomname,
  ROOMCODE, MID, CHECKIN, CHECKOUT
  FROM RESERVATION WHERE CHECKIN >= SYSDATE;
-- 예약 가능한지 여부 (roomCode, checkIn, checkOut 입력받음)
SELECT * FROM RESERVATION
  WHERE ROOMCODE=2 AND
    ( (CHECKIN <= '23/07/30' AND '23/08/01' <= CHECKOUT) OR
     ('23/07/30' < CHECKOUT  AND CHECKOUT < '23/08/01') OR
     ('23/07/30' < CHECKIN  AND CHECKIN < '23/08/01') OR
     ('23/07/30' < CHECKIN AND CHECKOUT < '23/08/01'));