-- TABLE DROP & CREATE
DROP TABLE MEMBER CASCADE CONSTRAINTS; 
CREATE TABLE MEMBER(
  ID VARCHAR2(30) PRIMARY KEY,
  PW VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  PHONE1 VARCHAR2(5),
  PHONE2 VARCHAR2(5),
  PHONE3 VARCHAR2(5),
  GENDER VARCHAR2(1),
  EMAIL VARCHAR2(30),
  BIRTH DATE,
  ADDRESS VARCHAR2(200),
  RDATE DATE NOT NULL -- 가입일
);
SELECT * FROM MEMBER;





