DROP SEQUENCE B_SEQ;
DROP TABLE B CASCADE CONSTRAINTS;
CREATE TABLE B(
    BNO NUMBER(9) PRIMARY KEY,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT CLOB,
    BFILE VARCHAR2(100)
);
CREATE SEQUENCE B_SEQ MAXVALUE 999999999 NOCYCLE NOCACHE;
INSERT INTO B VALUES (B_SEQ.NEXTVAL, '제목1','내용','nothing.jpg');
SELECT * FROM B;

DROP TABLE REPLY ;
CREATE TABLE REPLY (
    RNO NUMBER(9) PRIMARY KEY, -- 댓글번호
    BNO NUMBER(9) REFERENCES B(BNO), -- 글번호
    RCONTENT VARCHAR2(1000) NOT NULL, -- 댓글
    RIP VARCHAR2(100)  NOT NULL, -- ip
    RDATE DATE DEFAULT SYSDATE -- 댓글 등록일
);
DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ MAXVALUE 999999999 NOCACHE NOCYCLE;
INSERT INTO REPLY (RNO, BNO, RCONTENT, RIP) 
    VALUES (REPLY_SEQ.NEXTVAL, 1, '좋아요','192.168.10.30');
SELECT * FROM REPLY WHERE BNO=1 ORDER BY RDATE DESC;
SELECT * FROM REPLY WHERE RNO=1;
UPDATE REPLY SET RCONTENT = '수정함', RIP='192.168.10.30' WHERE RNO=1;
COMMIT;