DROP SEQUENCE B_SEQ;
DROP TABLE B CASCADE CONSTRAINTS;
CREATE TABLE B(
    BNO NUMBER(9) PRIMARY KEY,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT CLOB,
    BFILE VARCHAR2(100)
);
CREATE SEQUENCE B_SEQ MAXVALUE 999999999 NOCYCLE NOCACHE;
INSERT INTO B VALUES (B_SEQ.NEXTVAL, '제목1','내용','nothing.jpg');
SELECT BNO, BTITLE, BCONTENT, BFILE, (SELECT COUNT(*) FROM COMMENTS WHERE BNO=B.BNO) CNT
  FROM B ; -- DAO에 들어갈 QUERY 
SELECT BNO, BTITLE, BCONTENT, BFILE, (SELECT COUNT(*) FROM COMMENTS WHERE BNO=B.BNO) CNT
  FROM B WHERE BNO=1;
DROP TABLE COMMENTS ;
CREATE TABLE COMMENTS (
    cNO NUMBER(9) PRIMARY KEY, -- 댓글번호
    BNO NUMBER(9) REFERENCES B(BNO), -- 글번호
    cCONTENT VARCHAR2(1000) NOT NULL, -- 댓글
    cIP VARCHAR2(100)  NOT NULL, -- ip
    cDATE DATE DEFAULT SYSDATE -- 댓글 등록일
);
DROP SEQUENCE COMMENTS_SEQ;
CREATE SEQUENCE COMMENTS_SEQ MAXVALUE 999999999 NOCACHE NOCYCLE;
INSERT INTO COMMENTS (CNO, BNO, CCONTENT, CIP) 
    VALUES (COMMENTS_SEQ.NEXTVAL, 1, '좋아요','192.168.10.30');
SELECT * FROM COMMENTS WHERE BNO=1 ORDER BY RDATE DESC;
SELECT * FROM COMMENTS WHERE RNO=1;
UPDATE COMMENTS SET cCONTENT = '수정함', cIP='192.168.10.30' WHERE cNO=1;
COMMIT;